openapi: 3.0.3
info:
  title: Characters API
  description: In this api are located de endpoints to characters and tables
  version: 1.0.0

paths:
  /characters:
    get:
      tags:
        - characters
      summary: List all characters
      description: List all characters id and name
      operationId: findAllCharacters
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterItemCollection'
components:
  schemas:
    CharacterItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    CharacterItemCollection:
      type: array
      items:
        $ref: '#/components/schemas/CharacterItem'


