openapi: 3.0.3
info:
  title: Panels API
  description: api where is located the endpoints to panels
  version: 1.0.0

paths:
    /panels:
      get:
        tags:
          - panels
        summary: Lits of all panels
        description: List of all panels id and name
        operationId: findAllPanels
        responses:
          '200':
            description: susccesfull operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PanelItemCollection'
          '400':
            description: bad request
            content:
              application/json:
                schema:
                  type: string
          '404':
            description: request not found
            content:
              application/json:
                schema:
                  type: string
                  example: {"message":"Error 404. page or request not found."}
      post:
        tags:
          - panels
        summary: create a list of panel
        description: create a list of panel by id and name
        operationId: createPanel
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PanelItemCollection'
        responses:
          '200':
            description: creation susccesfull
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
          '400':
            description: bad request
            content:
              application/json:
                schema:
                  type: string
          '404':
            description: request not found
            content:
              application/json:
                schema:
                  type: string
                  example: { "message": "Error 404. page or request not found." }
          '500':
            description: server error
            content:
              application/json:
                schema:
                  type: string
      put:
        tags:
          - panels
        summary: Update list of panels
        description: Update list of panels by id and name
        operationId: updateAllPanels
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PanelItemCollection'
        responses:
          '200':
            description: Update susccesfull
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/PanelItemCollection'
          '400':
            description: bad request
            content:
              application/json:
                schema:
                  type: string
          '404':
            description: request not found
            content:
              application/json:
                schema:
                  type: string
                  example: { "message": "Error 404. page or request not found." }
          '500':
            description: server error
            content:
              application/json:
                schema:
                  type: string
      patch:
        tags:
          - panels
        summary: Parcially update list of panels
        description: Parcially update list of panels by id and name
        operationId: partialUpdateAllPanels
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PanelItemCollection'
        responses:
          '200':
            description: Update susccesfull
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/PanelItemCollection'
          '400':
            description: bad request
            content:
              application/json:
                schema:
                  type: string
          '404':
            description: request not found
            content:
              application/json:
                schema:
                  type: string
                  example: { "message": "Error 404. page or request not found." }
          '500':
            description: server error
            content:
              application/json:
                schema:
                  type: string
      delete:
        tags:
          - panels
        summary: Delete panels
        description: Delete panels by id and name
        operationId: deletePanel
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  ids:
                    type: array
                    items:
                      type: array
                      format: int64
                    description: Ids of panels to delete
        responses:
          '200':
            description: susccesfull operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PanelItemCollection'
          '400':
            description: bad request
            content:
              application/json:
                schema:
                  type: string
          '404':
            description: request not found
            content:
              application/json:
                schema:
                  type: string
                  example: { "message": "Error 404. page or request not found." }
          '500':
            description: server error
            content:
              application/json:
                schema:
                  type: string

components:
  schemas:
    PanelItemCollection:
      type: array
      items:
        $ref: '#/components/schemas/PanelItem'
    PanelItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string