openapi: 3.0.3
info:
  title: Panels API
  description: api where is located the endpoints to panels
  version: 1.0.0

paths:
    /panels:
      get:
        tags:
          - panels
        summary: Lits of all panels
        operationId: findAllPanels
        responses:
          '200':
            description: susccesfull operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PanelItemCollection'

components:
  schemas:
    PanelItemCollection:
      type: array
      items:
        $ref: '#/components/schemas/PanelItem'
    PanelItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string