version: '3'
services:

  db_postgres_anigames:
    image: postgres:11
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - postgresql:/var/lib/postgresql
      - postgres11-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"

volumes:
  postgresql:
  postgres11-data:
    driver: local